language: java
jdk:
  - oraclejdk8

os:
  - linux
dist: trusty

before_install:
  #load all submodules
  - git submodule init
  - git submodule update
  #update all repo lists
  - sudo apt-get update -y
  #install curl for tomcat tests
  - sudo apt-get install curl -y
  # get thrift 0.9.3
  - wget "https://www.dropbox.com/s/u4prfzehb94xo9n/thrift"
  - wget "https://www.dropbox.com/s/ydbf9ghsl6lv5dl/libthrift-0.9.3.jar"
  - chmod 755 thrift
  - sudo cp thrift /usr/local/bin/thrift
  - sudo cp libthrift-0.9.3.jar /usr/local/lib
  #fake random with urandom (do not repeat it on your own computer)
  - sudo rm /dev/random
  - sudo mknod /dev/random c 1 9

install:
  #install and run tests and run style checking
  - mvn install -P travis

script:
  #run services
  - cd db-services

  - cd db-diagram-service
  - mvn exec:java -P travis &
  - sleep 15

  - cd ../db-user-service
  - mvn exec:java -P travis &
  - sleep 15

  - cd ../db-robot-store-service
  - mvn exec:java -P travis &
  - sleep 15

  - cd ../../auth-service
  - mvn tomcat7:run-war-only -P travis &
  - sleep 30

  - cd  ../dashboard-service
  - mvn tomcat7:run-war-only -P travis &
  - sleep 30

  - cd ../editor-service
  - mvn tomcat7:run-war-only -P travis &
  - sleep 30

  - ../Travis/callTomcat.sh

notifications:
  slack: qreal-web:sT5qgA4qZZ9eyLI0yy2Mp81E
